/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/about/CGU/': RouteRecordInfo<'/about/CGU/', '/about/CGU', Record<never, never>, Record<never, never>>,
    '/about/legalNotices/': RouteRecordInfo<'/about/legalNotices/', '/about/legalNotices', Record<never, never>, Record<never, never>>,
    '/about/privacyPolicy/': RouteRecordInfo<'/about/privacyPolicy/', '/about/privacyPolicy', Record<never, never>, Record<never, never>>,
    '/app/challenges/': RouteRecordInfo<'/app/challenges/', '/app/challenges', Record<never, never>, Record<never, never>>,
    '/app/myProfile/': RouteRecordInfo<'/app/myProfile/', '/app/myProfile', Record<never, never>, Record<never, never>>,
    '/app/ranking/': RouteRecordInfo<'/app/ranking/', '/app/ranking', Record<never, never>, Record<never, never>>,
    '/app/userProfile/': RouteRecordInfo<'/app/userProfile/', '/app/userProfile', Record<never, never>, Record<never, never>>,
    '/auth/login/': RouteRecordInfo<'/auth/login/', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/register/': RouteRecordInfo<'/auth/register/', '/auth/register', Record<never, never>, Record<never, never>>,
    '/help/contact/': RouteRecordInfo<'/help/contact/', '/help/contact', Record<never, never>, Record<never, never>>,
    '/help/FAQ/': RouteRecordInfo<'/help/FAQ/', '/help/FAQ', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/about/CGU/index.vue': {
      routes: '/about/CGU/'
      views: never
    }
    'src/pages/about/legalNotices/index.vue': {
      routes: '/about/legalNotices/'
      views: never
    }
    'src/pages/about/privacyPolicy/index.vue': {
      routes: '/about/privacyPolicy/'
      views: never
    }
    'src/pages/app/challenges/index.vue': {
      routes: '/app/challenges/'
      views: never
    }
    'src/pages/app/myProfile/index.vue': {
      routes: '/app/myProfile/'
      views: never
    }
    'src/pages/app/ranking/index.vue': {
      routes: '/app/ranking/'
      views: never
    }
    'src/pages/app/userProfile/index.vue': {
      routes: '/app/userProfile/'
      views: never
    }
    'src/pages/auth/login/index.vue': {
      routes: '/auth/login/'
      views: never
    }
    'src/pages/auth/register/index.vue': {
      routes: '/auth/register/'
      views: never
    }
    'src/pages/help/contact/index.vue': {
      routes: '/help/contact/'
      views: never
    }
    'src/pages/help/FAQ/index.vue': {
      routes: '/help/FAQ/'
      views: never
    }
    'src/pages/home/index.vue': {
      routes: '/home/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
