/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/about/CGU/CGU': RouteRecordInfo<'/about/CGU/CGU', '/about/CGU/CGU', Record<never, never>, Record<never, never>>,
    '/about/legalNotices/LegalNotices': RouteRecordInfo<'/about/legalNotices/LegalNotices', '/about/legalNotices/LegalNotices', Record<never, never>, Record<never, never>>,
    '/about/privacyPolicy/PrivacyPolicy': RouteRecordInfo<'/about/privacyPolicy/PrivacyPolicy', '/about/privacyPolicy/PrivacyPolicy', Record<never, never>, Record<never, never>>,
    '/app/challenge/Challenge': RouteRecordInfo<'/app/challenge/Challenge', '/app/challenge/Challenge', Record<never, never>, Record<never, never>>,
    '/app/challenges/Challenges': RouteRecordInfo<'/app/challenges/Challenges', '/app/challenges/Challenges', Record<never, never>, Record<never, never>>,
    '/app/myProfile/MyProfile': RouteRecordInfo<'/app/myProfile/MyProfile', '/app/myProfile/MyProfile', Record<never, never>, Record<never, never>>,
    '/app/ranking/Ranking': RouteRecordInfo<'/app/ranking/Ranking', '/app/ranking/Ranking', Record<never, never>, Record<never, never>>,
    '/app/userProfile/UserProfile': RouteRecordInfo<'/app/userProfile/UserProfile', '/app/userProfile/UserProfile', Record<never, never>, Record<never, never>>,
    '/auth/login/Login': RouteRecordInfo<'/auth/login/Login', '/auth/login/Login', Record<never, never>, Record<never, never>>,
    '/auth/register/Register': RouteRecordInfo<'/auth/register/Register', '/auth/register/Register', Record<never, never>, Record<never, never>>,
    '/help/contact/Contact': RouteRecordInfo<'/help/contact/Contact', '/help/contact/Contact', Record<never, never>, Record<never, never>>,
    '/help/FAQ/FAQ': RouteRecordInfo<'/help/FAQ/FAQ', '/help/FAQ/FAQ', Record<never, never>, Record<never, never>>,
    '/home/Home': RouteRecordInfo<'/home/Home', '/home/Home', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/about/CGU/CGU.vue': {
      routes: '/about/CGU/CGU'
      views: never
    }
    'src/pages/about/legalNotices/LegalNotices.vue': {
      routes: '/about/legalNotices/LegalNotices'
      views: never
    }
    'src/pages/about/privacyPolicy/PrivacyPolicy.vue': {
      routes: '/about/privacyPolicy/PrivacyPolicy'
      views: never
    }
    'src/pages/app/challenge/Challenge.vue': {
      routes: '/app/challenge/Challenge'
      views: never
    }
    'src/pages/app/challenges/Challenges.vue': {
      routes: '/app/challenges/Challenges'
      views: never
    }
    'src/pages/app/myProfile/MyProfile.vue': {
      routes: '/app/myProfile/MyProfile'
      views: never
    }
    'src/pages/app/ranking/Ranking.vue': {
      routes: '/app/ranking/Ranking'
      views: never
    }
    'src/pages/app/userProfile/UserProfile.vue': {
      routes: '/app/userProfile/UserProfile'
      views: never
    }
    'src/pages/auth/login/Login.vue': {
      routes: '/auth/login/Login'
      views: never
    }
    'src/pages/auth/register/Register.vue': {
      routes: '/auth/register/Register'
      views: never
    }
    'src/pages/help/contact/Contact.vue': {
      routes: '/help/contact/Contact'
      views: never
    }
    'src/pages/help/FAQ/FAQ.vue': {
      routes: '/help/FAQ/FAQ'
      views: never
    }
    'src/pages/home/Home.vue': {
      routes: '/home/Home'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
